### PR TITLE
set and use isNavLocked observable

### PR DESCRIPTION
**Pull request by thompsongl**
Only thing I noticed is that there's a z-index issue when the nav is open but not locked (bottom bar is above the nav)

### CODE REVIEW

**Comment by cchaos** [comment]
Yeah, I should have the z-index issue fixed.

**Comment by cchaos** [comment]
Looking at this, we may want to do these as separate PR's. Since your code touches so much platform code, it'd be nice for it to stay focused.

**Comment by thompsongl** [comment]
I'm good with that. I can get one set up when you're all ready

**Comment by cchaos** [comment]
THanks. Definitely don't lose this work, because others will need it, but I'm still evaluating whether the control bar makes sense for Lens.

**Pull request closed without merging**
